apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io  
spec:
  description: Infrastructure project for monitoring and infrastructure components

  # Allow repositories for monitoring stack and infrastructure
  sourceRepos:
    - "https://github.com/rojanhero1/monitoring-ecosystem-gitops.git"
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    - "*"  # Allow any additional Helm charts or Git repos if needed

  # Allow deploying to all necessary namespaces for infrastructure components
  destinations:
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: "*"  # Allow any namespace for flexibility
    - server: "*"  # Allow any cluster if multi-cluster setup is needed
      namespace: "*"

  # Allow all cluster-scoped resources (needed for CRDs, ClusterRoles, etc.)
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # Allow all namespace-scoped resources
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Orphaned resources handling
  orphanedResources:
    warn: true

  # Optional: Role definitions for project-level RBAC
  roles:
    - name: admin
      description: Admin privileges for infra project
      policies:
        - p, proj:infra:admin, applications, *, infra/*, allow
      groups:
        - infra-admins

    - name: developer
      description: Developer privileges for infra project
      policies:
        - p, proj:infra:developer, applications, get, infra/*, allow
        - p, proj:infra:developer, applications, sync, infra/*, allow
      groups:
        - infra-developers
