repo-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: personal-github-repo
  url: https://github.com/rojanhero1/monitoring-ecosystem-gitops.git
  username: usrname
  password: github-token