apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd         # <== ArgoCD's namespace
spec:
  project: default          # or your Argo project
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: 2.52.1          # matches what you have installed
    helm:
      values: |
        controller:
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::687398153695:role/Cloudhero-staging-eks-EBSCSIIRSA
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true     # <== Better conflict handling      